import plot_seasonality
import read_files

dict_seasonality = read_files.read_vars_per_months()
plot_seasonality.plot_all_seasonality(dict_seasonality)
plot_seasonality.plot_seasonality_region(dict_seasonality)
